# ===================================================================
# Application Core Profiles & Threading
# ===================================================================
spring.application.name=trimlink-url-shortener
server.port=8080

# Tomcat's thread pool configured to handle concurrent requests under load
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20

# ===================================================================
# Relational Database Configuration (PostgreSQL / Source of Truth)
# ===================================================================
# 'postgres-db: database container inside the Docker network
spring.datasource.url=jdbc:postgresql://postgres-db:5432/shortener_db
spring.datasource.username=postgres_user
spring.datasource.password=secure_db_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Management (HikariCP)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000

# Hibernate / JPA Strategy
# 'update' automatically updates the schema structures if our entities change
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# Cache Layer Configuration (Centralized Redis Cache)
# ===================================================================
# 'redis-cache': Redis instance in docker-compose
spring.data.redis.host=redis-cache
spring.data.redis.port=6373
spring.data.redis.timeout=2000
spring.data.redis.password=secure_redis_password